# Generated by Django 4.2.11 on 2024-08-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transcription",
            name="processed",
        ),
        migrations.AddField(
            model_name="transcription",
            name="transcript",
            field=models.TextField(blank=True),
        ),
    ]
